spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            token-uri: https://dev-75166832.okta.com/oauth2/default/v1/token
        registration:
          okta:
            client-id: ${clientId}
            client-secret: ${clientSecret}
            scope: Custom_Scope
            authorization-grant-type: client_credentials
server:
  port: 8090
