spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            token-uri: https://dev-75166832.okta.com/oauth2/default/v1/token
        registration:
          okta:
            client-id: 0oa5a815y0AtNAPNI5d7
            client-secret: IZjsoXulj146gd-1gDe3bOdS6t67Z-E4I--M_uwP
            scope: Custom_Scope
            authorization-grant-type: client_credentials
server:
  port: 8090
